#!/bin/bash

# Find and kill processes with 'helics' in the name

# Get the process IDs (PIDs) of processes containing 'helics'
processes=$(ps aux | grep -i 'helics' | grep -v grep | awk '{print $2}')

# Check if any processes were found
if [ -z "$processes" ]; then
  echo "No processes with 'helics' in the name were found."
else
  # Loop through each PID and kill the process
  echo "Killing the following processes with 'helics' in the name:"
  echo "$processes"
  for pid in $processes; do
    kill -9 $pid
    if [ $? -eq 0 ]; then
      echo "Successfully killed process $pid"
    else
      echo "Failed to kill process $pid"
    fi
  done
fi